import {
    siLaravel,
    siReact,
    siTypescript,
    siGo,
    siPhp,
    siPostgresql,
    siMysql,
    siDocker,
    siJavascript,
    siNodedotjs,
    siGit,
    siTailwindcss,
    siRedis,
    siLinux,
    siKubernetes,
    siVuedotjs,
    siAngular,
    siPython,
    siRust,
    siSwift,
    siKotlin,
    siFlutter,
    siDart,
    siNextdotjs,
    siNuxt,
    siMongodb,
    siGraphql,
    siSass,
    siCss,
    siHtml5,
    siNginx,
    siApache,
    siFigma,
    siGithub,
    siGitlab,
    siBitbucket,
    siVim,
    siNeovim,
    siUbuntu,
    siDebian,
    siCentos,
    siAlpinelinux,
    siTerraform,
    siAnsible,
    siJenkins,
    siVercel,
    siNetlify,
    siCloudflare,
    siDigitalocean,
    siFirebase,
    siSupabase,
    siPrisma,
    siExpress,
    siFastify,
    siNestjs,
    siDjango,
    siFlask,
    siRubyonrails,
    siRuby,
    siSpring,
    siDotnet,
    siElectron,
    siTauri,
    siExpo,
    siWebpack,
    siVite,
    siRollupdotjs,
    siEsbuild,
    siBun,
    siDeno,
    siPnpm,
    siNpm,
    siYarn,
    siJest,
    siVitest,
    siCypress,
    siStorybook,
    siStripe,
    siDiscord,
    siTelegram,
    siWordpress,
    siShopify,
    siInertia,
    siLivewire,
    siFilament,
} from 'simple-icons';

export const techIcons: Record<string, { title: string; slug: string; hex: string; svg: string }> = {
    laravel: siLaravel,
    react: siReact,
    typescript: siTypescript,
    go: siGo,
    php: siPhp,
    postgresql: siPostgresql,
    mysql: siMysql,
    docker: siDocker,
    javascript: siJavascript,
    nodedotjs: siNodedotjs,
    git: siGit,
    tailwindcss: siTailwindcss,
    redis: siRedis,
    linux: siLinux,
    kubernetes: siKubernetes,
    vuedotjs: siVuedotjs,
    angular: siAngular,
    python: siPython,
    rust: siRust,
    swift: siSwift,
    kotlin: siKotlin,
    flutter: siFlutter,
    dart: siDart,
    nextdotjs: siNextdotjs,
    nuxtdotjs: siNuxt,
    mongodb: siMongodb,
    graphql: siGraphql,
    sass: siSass,
    css3: siCss,
    html5: siHtml5,
    nginx: siNginx,
    apache: siApache,
    figma: siFigma,
    github: siGithub,
    gitlab: siGitlab,
    bitbucket: siBitbucket,
    vim: siVim,
    neovim: siNeovim,
    ubuntu: siUbuntu,
    debian: siDebian,
    centos: siCentos,
    alpinelinux: siAlpinelinux,
    terraform: siTerraform,
    ansible: siAnsible,
    jenkins: siJenkins,
    vercel: siVercel,
    netlify: siNetlify,
    cloudflare: siCloudflare,
    digitalocean: siDigitalocean,
    firebase: siFirebase,
    supabase: siSupabase,
    prisma: siPrisma,
    express: siExpress,
    fastify: siFastify,
    nestjs: siNestjs,
    django: siDjango,
    flask: siFlask,
    rubyonrails: siRubyonrails,
    ruby: siRuby,
    spring: siSpring,
    dotnet: siDotnet,
    electron: siElectron,
    tauri: siTauri,
    expo: siExpo,
    webpack: siWebpack,
    vite: siVite,
    rollupdotjs: siRollupdotjs,
    esbuild: siEsbuild,
    bun: siBun,
    deno: siDeno,
    pnpm: siPnpm,
    npm: siNpm,
    yarn: siYarn,
    jest: siJest,
    vitest: siVitest,
    cypress: siCypress,
    storybook: siStorybook,
    stripe: siStripe,
    discord: siDiscord,
    telegram: siTelegram,
    wordpress: siWordpress,
    shopify: siShopify,
    inertia: siInertia,
    livewire: siLivewire,
    filament: siFilament,
};

export const techToSimpleIconSlug: Record<string, string> = {
    laravel: 'laravel',
    react: 'react',
    typescript: 'typescript',
    golang: 'go',
    go: 'go',
    php: 'php',
    postgresql: 'postgresql',
    postgres: 'postgresql',
    mysql: 'mysql',
    docker: 'docker',
    javascript: 'javascript',
    js: 'javascript',
    nodejs: 'nodedotjs',
    node: 'nodedotjs',
    git: 'git',
    tailwindcss: 'tailwindcss',
    tailwind: 'tailwindcss',
    redis: 'redis',
    linux: 'linux',
    aws: 'amazonwebservices',
    kubernetes: 'kubernetes',
    k8s: 'kubernetes',
    vue: 'vuedotjs',
    vuejs: 'vuedotjs',
    angular: 'angular',
    python: 'python',
    java: 'java',
    rust: 'rust',
    swift: 'swift',
    kotlin: 'kotlin',
    flutter: 'flutter',
    dart: 'dart',
    nextjs: 'nextdotjs',
    next: 'nextdotjs',
    nuxt: 'nuxtdotjs',
    nuxtjs: 'nuxtdotjs',
    mongodb: 'mongodb',
    mongo: 'mongodb',
    graphql: 'graphql',
    sass: 'sass',
    scss: 'sass',
    css: 'css3',
    html: 'html5',
    nginx: 'nginx',
    apache: 'apache',
    figma: 'figma',
    github: 'github',
    gitlab: 'gitlab',
    bitbucket: 'bitbucket',
    vscode: 'visualstudiocode',
    vim: 'vim',
    neovim: 'neovim',
    ubuntu: 'ubuntu',
    debian: 'debian',
    centos: 'centos',
    alpine: 'alpinelinux',
    terraform: 'terraform',
    ansible: 'ansible',
    jenkins: 'jenkins',
    vercel: 'vercel',
    netlify: 'netlify',
    cloudflare: 'cloudflare',
    digitalocean: 'digitalocean',
    heroku: 'heroku',
    firebase: 'firebase',
    supabase: 'supabase',
    prisma: 'prisma',
    express: 'express',
    fastify: 'fastify',
    nestjs: 'nestjs',
    django: 'django',
    flask: 'flask',
    rails: 'rubyonrails',
    ruby: 'ruby',
    spring: 'spring',
    dotnet: 'dotnet',
    csharp: 'csharp',
    electron: 'electron',
    tauri: 'tauri',
    reactnative: 'react',
    expo: 'expo',
    webpack: 'webpack',
    vite: 'vite',
    rollup: 'rollupdotjs',
    esbuild: 'esbuild',
    bun: 'bun',
    deno: 'deno',
    pnpm: 'pnpm',
    npm: 'npm',
    yarn: 'yarn',
    jest: 'jest',
    vitest: 'vitest',
    playwright: 'playwright',
    cypress: 'cypress',
    storybook: 'storybook',
    stripe: 'stripe',
    twilio: 'twilio',
    slack: 'slack',
    discord: 'discord',
    telegram: 'telegram',
    wordpress: 'wordpress',
    shopify: 'shopify',
    magento: 'magento',
    inertia: 'inertia',
    livewire: 'livewire',
    filament: 'filament',
};
